/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import enums.FormaPagamento;
import model.Item;
import model.Venda;
import util.BaseDeDados;

/**
 *
 * @author Win
 */
public class DlgConfirmaPagamento extends javax.swing.JDialog {

    /**
     * Creates new form DlgConfirmaPagamento
     */
    private Venda venda;

    public DlgConfirmaPagamento(java.awt.Frame parent, boolean modal, Venda venda) {
        super(parent, modal);
        initComponents();

        this.venda = venda;
        inicia();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVenda = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtPrecoTotal = new javax.swing.JTextField();
        lblFormaPagamento = new javax.swing.JLabel();
        cbPagamento = new javax.swing.JComboBox();
        btConcluir = new javax.swing.JButton();
        lblValorPago = new javax.swing.JLabel();
        lblTroco = new javax.swing.JLabel();
        txtValorPago = new javax.swing.JTextField();
        txtTroco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblPreco.setText("Preço Total:");

        lblFormaPagamento.setText("forma de Pagamento:");

        cbPagamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPagamentoItemStateChanged(evt);
            }
        });

        btConcluir.setText("Concluir");
        btConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConcluirActionPerformed(evt);
            }
        });

        lblValorPago.setText("Valor pago:");
        lblValorPago.setToolTipText("");

        lblTroco.setText("Troco:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btConcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFormaPagamento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPreco)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTroco)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTroco))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblValorPago)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(txtPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormaPagamento)
                    .addComponent(cbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorPago)
                    .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTroco)
                    .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPagamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPagamentoItemStateChanged
        FormaPagamento aux = (FormaPagamento) cbPagamento.getSelectedItem();
        if (aux == FormaPagamento.CARTAO) {

            txtValorPago.setText(txtPrecoTotal.getText());
            txtTroco.setText("0");

        }

    }//GEN-LAST:event_cbPagamentoItemStateChanged

    private void btConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConcluirActionPerformed
        if ((!txtValorPago.getText().equals("") && !txtTroco.getText().equals(""))) {

            this.venda.setFormaPagamento((FormaPagamento) cbPagamento.getSelectedItem());
            this.venda.setValorPago(Double.parseDouble(txtValorPago.getText()));
            this.venda.setTroco(Double.parseDouble(txtTroco.getText()));
            BaseDeDados.getInstance().getVendas().add(venda);
            System.out.println("Cadastrou , é gol , passou nessa porra!");
            this.dispose();
        }
    }//GEN-LAST:event_btConcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConcluir;
    private javax.swing.JComboBox cbPagamento;
    private javax.swing.JLabel lblFormaPagamento;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblValorPago;
    private javax.swing.JLabel lblVenda;
    private javax.swing.JTextField txtPrecoTotal;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtValorPago;
    // End of variables declaration//GEN-END:variables

    private void preencheTiposPagamento() {

        cbPagamento.addItem(FormaPagamento.CARTAO);
        cbPagamento.addItem(FormaPagamento.DINHEIRO);

    }

    private void inicia() {
        double aux = 0;

        lblVenda.setText(this.venda.toString());
        for (Item item : venda.getItens()) {
            aux += item.getPreco() * item.getQuantidade();
        }

        txtPrecoTotal.setText(String.valueOf(aux));

        preencheTiposPagamento();

    }
}
