/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Fernando
 */
public class PnlEditaEstoque extends javax.swing.JPanel {

    /**
     * Creates new form PnlEditaEstoque
     */
    public PnlEditaEstoque() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCriaProduto = new javax.swing.JButton();
        btnEditaProduto = new javax.swing.JButton();
        btnCriaEstoque = new javax.swing.JButton();
        btnEditaEstoque = new javax.swing.JButton();

        btnCriaProduto.setText("Cadastrar Produtos");
        btnCriaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriaProdutoActionPerformed(evt);
            }
        });

        btnEditaProduto.setText("Edita/Exclui Produtos");
        btnEditaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditaProdutoActionPerformed(evt);
            }
        });

        btnCriaEstoque.setText("Cadastrar Estoque de Produto");
        btnCriaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriaEstoqueActionPerformed(evt);
            }
        });

        btnEditaEstoque.setText("Editar/Excluir Estoque");
        btnEditaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditaEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCriaEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCriaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(btnEditaEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCriaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(btnEditaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCriaEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(btnEditaEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriaProdutoActionPerformed
        DlgCriaProduto dlgCriaProduto = new DlgCriaProduto(null, true);
        dlgCriaProduto.setVisible(true);
    }//GEN-LAST:event_btnCriaProdutoActionPerformed

    private void btnEditaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditaProdutoActionPerformed
        DlgEditaProduto dlgEditaProduto = new DlgEditaProduto(null, true);
        dlgEditaProduto.setVisible(true);
    }//GEN-LAST:event_btnEditaProdutoActionPerformed

    private void btnCriaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriaEstoqueActionPerformed
        DlgCriaEstoque dlgCriaEstoque = new DlgCriaEstoque(null, true);
        dlgCriaEstoque.setVisible(true);
    }//GEN-LAST:event_btnCriaEstoqueActionPerformed

    private void btnEditaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditaEstoqueActionPerformed
        DlgEditaEstoque dlgEditaEstoque = new DlgEditaEstoque(null, true);
        dlgEditaEstoque.setVisible(true);
    }//GEN-LAST:event_btnEditaEstoqueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriaEstoque;
    private javax.swing.JButton btnCriaProduto;
    private javax.swing.JButton btnEditaEstoque;
    private javax.swing.JButton btnEditaProduto;
    // End of variables declaration//GEN-END:variables

}
